### ISSUE TITLE
Request: Boolean types

### ISSUE THREAD

**Issue by alfiedotwtf** [rjbs/JSON-Typist#1]
It would be useful if there were Boolean types too.

**Comment by rjbs** [comment]
JSON already uses objects for booleans:

```
~$ perl -MJSON -E 'say ref JSON->new->decode("[true]")->[0]'
JSON::PP::Boolean
```

**Comment by alfiedotwtf** [comment]
Interestingly when I run the same code, I get back:

```
JSON::XS::Boolean
```

**Comment by rjbs** [comment]
You'd get PP if you were running JSON::XS v3 or newer.

**Comment by alfiedotwtf** [comment]
+1 Awesome, thanks!
